name: Test API
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        # First Run ls
        run: git clone https://github.com/daovitou/devops-2.git
      - name: List folders
        # First Run ls
        run: ls